trigger:
- main

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'ACRTest1'
    repository: 'test435435'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
